import { ProductPreview } from 'src/app/interfaces/product-preview';

export const items: ProductPreview[] = [
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
  {
    handle: '',
    title: '',
    price: '',
    address: '',
    city: '',
    province: '',
    image: '',
    category: '',
  },
];
